/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:23b5a5a0-baab-40b5-81ee-072995ca0cf7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jdWKIS1qd",
    "aws_user_pools_web_client_id": "28jar0851r1st3theulfrc6rb0",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "amplifyuser-20221022233347-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplifyuser-20221022233347-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_user_files_s3_bucket": "serverless-dataset-storage",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
